---
- hosts: all
  pre_tasks:
    - name: Install python-pip.
      apt:
        name: python-pip
        state: present
        update_cache: yes
        cache_valid_time: 3600
  roles:
    - role: distractinator
