---
- name: Add user to dialout group.
  become: yes
  user:
    name: "{{ distractinator_user }}"
    groups: dialout
    append: yes

- name: Install distractinator pip package.
  pip:
    name: distractinator
    state: present
    extra_args: "{{ '--user' if distractinator_user_install else '' }}"
  when: "'VIRTUAL_ENV' not in ansible_env"

- name: Create custom events config directory.
  file:
    path: "{{ distractinator_custom_events_dest|dirname }}"
    state: directory
  when: distractinator_custom_events_src != ''

- name: Copy custom events file.
  copy:
    src: "{{ distractinator_custom_events_src }}"
    dest: "{{ distractinator_custom_events_dest }}"
  when: distractinator_custom_events_src != ''
  notify: restart distractd

- name: Update config file with custom events path.
  ini_file:
    dest: "{{ ('~'+distractinator_user+'/.distractinator.conf')|expanduser }}"
    section: notifier
    option: custom_script
    value: "{{ distractinator_custom_events_dest|expanduser}}"
  notify: restart distractd

- name: Create systemd user config directory for distractd.
  file:
    path: "{{ ('~'+distractinator_user+'/.config/systemd/user')|expanduser }}"
    state: directory
  when: distractinator_user_install

- name: Set up systemd service file for distractd.
  copy:
    src: distractd.service
    dest: "{{ ('~'+distractinator_user+'/.config/systemd/user/distractd.service')|expanduser }}"
  when: distractinator_user_install

- name: Start distractd service.
  systemd:
    name: distractd
    state: started
    enabled: yes
    user: "{{ distractinator_user_install }}"
