---
- name: Add user to dialout group.
  become: yes
  user:
    name: "{{ distractinator_user }}"
    groups: dialout
    append: yes

- name: Install distractinator pip package.
  pip:
    name: distractinator
    state: present
    extra_args: "{{ '--user' if distractinator_user_install else '' }}"
  when: "'VIRTUAL_ENV' not in ansible_env"

- name: Copy custom events file.
  copy:
    src: "{{ distractinator_custom_events_src }}"
    dest: "{{ distractinator_custom_events_dest }}"
  when: distractinator_custom_events_src

- name: Set up systemd service file for distractd.
  copy:
    src: distractd.service
    dest: ~/.config/systemd/user/distractd.service

- name: Start distractd service.
  systemd:
    name: distractd
    state: started
    enabled: yes
    user: "{{ distractinator_user_install }}"
